# -*- coding: utf-8 -*-
"""BoW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkpT-OYS4pEU_DAmPlBZePcWwOWOzuTg
"""

class BOWModel:
  def __init__(self):
      self.vocabulary = ['bank', 'fish', 'have', 'money', 'on', 'paid', 'river', 'stood', 'that','they', 'to', 'the', 'yet', 'you']
      self.word_to_index = {word: idx for idx, word in enumerate(self.vocabulary)}

  def process_text(self, text):
      words = text.lower().split()
      results = []
      for word in words:
          vector = [0] * len(self.vocabulary)
          if word in self.word_to_index:
              vector[self.word_to_index[word]] = 1

          results.append((word, vector))

      return results

  def display_results(self, results):
      print("\nBOW Representations:")
      print("-" * 50)
      for word, vector in results:
          print(f"Word: {word}")
          print(f"Vector: {vector}")
          print("-" * 50)

def main():
    bow = BOWModel()
    print("請輸入你的文字我幫你轉向量：")
    text = input()
    results = bow.process_text(text)
    bow.display_results(results)

if __name__ == "__main__":
    main()

